### ISSUE TITLE
creating imgui skeet.cc menu into this

### ISSUE THREAD

**Issue by profunderscorep** [0xSandman/smrfngsrryHOOK#1]
bro hello i realy want skeet menu in this hack, how do i paste it?
https://upload.wikimedia.org/wikipedia/commons/7/70/Skeet_menu.png

**Comment by iFloody** [comment]
Open your menu.cpp and replace with skeets menu.cpp.

**Comment by profunderscorep** [comment]
thxxxxxxxxxxxxxxxx it workssssssssssssssssssssssssssssssssssssssssss

**Comment by swoopae** [comment]
closed problem solved
pm if you need help hooking imgui d3d
